# Generated by Django 5.2.9 on 2025-12-24 02:04

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': '이미 사용 중인 아이디입니다.'}, help_text='4~20자, 영문으로 시작, 영문/숫자만 가능', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='아이디는 최소 4자 이상이어야 합니다.'), django.core.validators.RegexValidator(message='아이디는 영문으로 시작하고 영문, 숫자만 사용 가능합니다.', regex='^[a-zA-Z][a-zA-Z0-9]*$')])),
                ('nickname', models.CharField(error_messages={'unique': '이미 사용 중인 닉네임입니다.'}, help_text='2~15자, 한글/영문/숫자만 가능', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='닉네임은 최소 2자 이상이어야 합니다.'), django.core.validators.RegexValidator(message='닉네임은 한글, 영문, 숫자만 사용 가능합니다.', regex='^[가-힣a-zA-Z0-9]+$')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
