# Generated by Django 5.2.9 on 2025-12-24 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자들'},
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용 중인 닉네임입니다.'}, help_text='2~15자, 한글/영문/숫자만 가능', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='닉네임은 최소 2자 이상이어야 합니다.'), django.core.validators.RegexValidator(message='닉네임은 한글, 영문, 숫자만 사용 가능합니다.', regex='^[가-힣a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '이미 사용 중인 아이디입니다.'}, help_text='4~20자, 영문으로 시작, 영문/숫자만 가능', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='아이디는 최소 4자 이상이어야 합니다.'), django.core.validators.RegexValidator(message='아이디는 영문으로 시작하고 영문, 숫자만 사용 가능합니다.', regex='^[a-zA-Z][a-zA-Z0-9]*$')]),
        ),
    ]
