# Generated by Django 5.2.9 on 2025-12-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('effect', models.TextField()),
                ('usage', models.TextField()),
                ('warning', models.TextField()),
                ('symptoms', models.ManyToManyField(related_name='drugs', to='ingredients.symptom')),
            ],
        ),
    ]
