# Generated by Django 5.2.9 on 2025-12-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
