# Generated by Django 5.2.9 on 2025-12-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='symptom',
            name='drugs',
            field=models.ManyToManyField(related_name='symptoms', to='ingredients.drug'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='effect',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='usage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='warning',
            field=models.TextField(blank=True),
        ),
    ]
